import '../js/content.js'
import '../js/burgerMenu.js'
import '../js/feedback.js'
import '../js/call.js'
import '../js/repair-brands.js'
import '../js/repair-tech.js'
import '../js/repair-prices.js'
import '../scss/style.scss'
